### ISSUE TITLE
Lofi Designs maken

### ISSUE THREAD

**Issue by rutgerkock** [rutgerkock/your-tribe-for-life-squad-page#1]

**Comment by Anna-Kyra** [comment]
## Groffe schetsen Anna-Kyra
Ik heb voor de squad page lofi design 2 groffe idee schetsen gemaakt

### Kaart spel
![Image](https://github.com/user-attachments/assets/3048a739-1e0b-4627-a5cb-11dee0dcb34e)

Hierbij is het idee om iedereen als een kaart van een kaartspel te maken. Je hebt twee 'speel' pagina's een dealer waarbij je bijvoorbeeld 3 kaarten/personen word gedeeld en die open moet slaan om zo informatie van een persoon te zien krijgt. Het idee hierbij is om op een random manier mensen te zien van het 2e leerjaar.

Om een overzicht te krijgen van iedereen is er in een basic grid alle kaarten te zien.

Voor de mobile versie was het idee om te scrollen met de kaarten die al gezien zijn nog een beetje laten zien. Dat ze blijven staan op een punt.

### Where's Waldo

![Image](https://github.com/user-attachments/assets/049b5942-e6c0-4b1a-a8f4-9aeca7fa3f81)
Het idee was om een soort van waar is Waldo game te maken, maar dan met mensen van het 2e leerjaar + docenten. In de `h1` komt dan een naam te staan die je zou moeten zoeken. Eerst begint het tussen twee mensen kiezen en daarna wordt het moeilijker en komen er meerdere hoofden erbij bij elk level. Je hebt bijvoorbeeld 3 levens en dan begin je weer wat makkelijker.

Wanneer iemand is gevonden komen de gegevens van dat persoon te staan en kan je naar het visitekaartje navigeren.

De mensen die door de speler gevonden zijn worden opgezocht in de catalogus (zie rechts boven van schets). En hier staan ook mensen met vraagtekens wie je nog moet vinden.

Met de gene die je hebt gevonden wilde ik een soort verbindings gevoel geven. Dit had ik nog niet helemaal rond. Voor nu was het idee om met mensen die je had gevonden mee kon chatten

**Comment by TomDeeterink1** [comment]
# **Social media idee tom** 

Mijn idee was om een meer zakelijke aproach te doen zoals linkedin. Dit met rechthoekig vormen en zakelijke kleuren.

De bedoeling is dat mensen elkaar kunnen opzoeken, en elkaars socials in de gaten kan houden.

![Image](https://github.com/user-attachments/assets/350a34b0-4e85-47be-b3fd-36b845ac2d3a)

**Comment by Seijno** [comment]
# grove schetsen Seijno
Ik heb hier een ontwerp voor gemaakt met inspiratie

### kaartensets

![Image](https://github.com/user-attachments/assets/0629ce48-da7c-4538-b4da-31880e37d1b5)

Het leek me leuk om een soort collectable tafel te maken met alle leerlingen in groepjes bij elkaar, dit kan je met filters doen als bijv. op naam:


![Image](https://github.com/user-attachments/assets/9a7cb7f0-3116-4b1a-a49f-c17b9ac03b59)

### Mobile
Aangezien het een stuk lastiger wordt om dat op een leuke manier over te brengen naar mobile kreeg ik een leuk idee. Wat nou als we de pokedex gebruiken zoals in de games? Dit werd mijn inspiratie:



![Image](https://github.com/user-attachments/assets/3ee26e13-90ec-4172-88b4-2b7e94cdd4a2)

**Comment by Shannafdnd** [comment]
Ik heb een lofi schets gemaakt voor de squad page. Links in de schets zijn de squads te zien, met de avatars van alle personen in de squad. Rechts is een klein forum voor berichten, waar je elkaar kunt helpen en updates kan geven. Wanneer je op een persoon klikt zie je een detailpagina. Hier heb ik ook een schets voor gemaakt. Boven zie je de belangrijke informatie van het persoon, en onder zie je watvoor posts diegene heeft gemaakt. Je kan posts ook liken, en zien hoeveel likes een post heeft.

![Image](https://github.com/user-attachments/assets/4c9e54a3-667b-4d20-a381-e6eee8f805b3)


![Image](https://github.com/user-attachments/assets/6c854c20-7eed-4434-a122-668d717d9a6e)

**Comment by rutgerkock** [comment]
Mijn lofi ontwerp voor de squad-page. Het idee was dat de text squad voorbij komt en dat er dan knoppen verschijnen. Vervolgens krijg je allemaal tegels met namen en een zoekfunctie. Niet een te druk design maar wel overzichtelijk en functioneel.
![image](https://github.com/user-attachments/assets/b14fbefd-67c0-4861-b828-a1a69d13d105)
