### ISSUE TITLE
layout pagina

### ISSUE THREAD

**Issue by rutgerkock** [rutgerkock/your-tribe-for-life-squad-page#10]

**Comment by Seijno** [comment]
Voor deze taak moest een layout gemaakt worden, de DOD was als de layout klopt volgens het figma design:
![image](https://github.com/user-attachments/assets/58207560-fde6-4836-8b69-102fb52aee15)

Hiermee heb ik dit kunnen realiseren: 
<img src="https://github.com/user-attachments/assets/37ff8a15-f841-49ec-852b-61df54d25ede" width=700>

Ook is het gelijk responsive genoeg voor gebruikers op kleinere schermen:
<img src="https://github.com/user-attachments/assets/4b8cddb7-8efb-476e-9693-1b0a98b13ff2" height=400>
