### ISSUE TITLE
Svelte 500 internal error bug

### ISSUE THREAD

**Issue by Anna-Kyra** [rutgerkock/your-tribe-for-life-squad-page#14]
Er is een error in het [svelte.config.js](https://github.com/rutgerkock/your-tribe-for-life-squad-page/blob/2ba1a146a84bc80f47bfb20ffc0665aacd363afe/svelte.config.js#L1C1-L18C23) bestand. Hierdoor word er een 500 internal error weergegeven bij localhost link.

![Image](https://github.com/user-attachments/assets/87ab9212-ac82-46ad-a12d-9d63c491aca8)
![Image](https://github.com/user-attachments/assets/365a9d05-a09c-4e0e-adb1-3059ca8ce69f)

**Comment by Seijno** [comment]
Om de 500 error op te lossen, is het nodig dat je in je files een `.env` file maakt met daarin een link naar de DataBase in dit geval: `PUBLIC_APIURL = https://fdnd.directus.app/`
