### ISSUE TITLE
Kaarten flippen

### ISSUE THREAD

**Issue by Anna-Kyra** [rutgerkock/your-tribe-for-life-squad-page#30]

**Comment by Shannafdnd** [comment]
Ik heb de card flip gemaakt. Ik heb er js voor gebruikt omdat er al een hover animatie was. Het was wel iets anders dan gewone js, want het werkte niet met classlist.toggle, dus nu is er een functie voor:

  let currentFlippedCard = null
    function flipCard(person_id) {
        if (currentFlippedCard === person_id) {
            currentFlippedCard = null
        } else {
            currentFlippedCard = person_id
        }
    }
Hier word opgeslagen op welke kaart op dit moment omgedraaid moet zijn. currentFlippedCard is de id van de persoon van de kaart die nu omgedraaid is.
In de html staat:

<li class:flipped={currentFlippedCard === person.id}>
Dit zorgt ervoor dat alleen de kaart die geselecteerd is de flipped class krijgt.

Nu ziet het er zo uit:
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/843df265-973d-4db4-97de-1f02af2f148d">
