### ISSUE TITLE
aanmaken filters

### ISSUE THREAD

**Issue by rutgerkock** [rutgerkock/your-tribe-for-life-squad-page#8]

**Comment by Shannafdnd** [comment]
Ik heb filters gemaakt voor de verschillende squads. Dit zijn links gestyled om op een knop te lijken, en die nemen je naar een nieuwe pagina waar een filter in de link staat. Hiervoor heb ik een nieuw mapje in de route gemaakt genaamd squad[squad].

Verder heb ik ook een tutorial gevolgd voor een search filter. Deze tutorial gebruikt een store om search data data te storen. Het gebruikt ook commands als subscribe en unsubscribe. Dit is nog nieuw, dus ik heb hier bronnen bij gezet.

Ik heb groen gebruikt voor de knoppen, maar dit kan worden aangepast. 
![image](https://github.com/user-attachments/assets/fca89c3f-eb18-4c90-a2e2-aca7b219d5fd)
